// apps/blog/src/app/blog/[slug]/page.tsx
import { notFound } from 'next/navigation';
import { getAllPosts } from '@/lib/posts';
import { formatDate } from '@/lib/utils';

// Generate static params for all published posts
export function generateStaticParams() {
	const posts = getAllPosts();
	return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
	const { slug } = await params;
	const posts = getAllPosts();
	const post = posts.find((p) => p.slug === slug);
	if (!post) return {};
	return {
		title: post.title,
		description: post.description,
		openGraph: {
			type: 'article',
			title: post.title,
		},
	};
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
	const { slug } = await params;
	const posts = getAllPosts();
	const post = posts.find((p) => p.slug === slug);
	if (!post) notFound();

	// Dynamic import of the MDX file
	let PostContent: React.ComponentType;
	try {
		const mod = await import(`../../../../../../packages/content/posts/${slug}.mdx`);
		PostContent = mod.default;
	} catch {
		notFound();
	}

	return (
		<article className="max-w-prose mx-auto">
			<hgroup>
				<h1 className="text-3xl font-bold capitalize">{post.title}</h1>
			</hgroup>
			<div className="prose mt-8">
				<PostContent />
			</div>
			<p className="mt-8 text-muted-foreground">Published at {formatDate(post.date)}</p>
		</article>
	);
}

// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
	import { formatDate } from '$lib/utils';
	export let data;
</script>

<svelte:head>
	<title>{data.meta.title}</title>
	<meta property="og:type" content="article" />
	<meta property="og:title" content={data.meta.title} />
</svelte:head>

<article>
	<hgroup>
		<h1>{data.meta.title}</h1>
	</hgroup>

	{#if data.interactive}
		<div class="interactive-post">
			<svelte:component this={data.content} />
		</div>
	{:else}
		<div class="prose">
			<svelte:component this={data.content} />
		</div>
	{/if}

	<p>Published at {formatDate(data.meta.date)}</p>
</article>

<style>
	article {
		max-inline-size: var(--size-content-3);
		margin-inline: auto;
	}
	h1 {
		text-transform: capitalize;
	}
	h1 + p {
		margin-top: var(--size-2);
		color: var(--text-2);
	}
	.interactive-post {
		margin-top: var(--size-7);
	}
</style>
